# Generated by Django 5.0.6 on 2025-07-01 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteB2B',
            fields=[
                ('id_cliente_b2b', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=12)),
                ('correo_empresa', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cliente_b2b',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteB2C',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cliente_b2c',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
            ],
            options={
                'db_table': 'cotizacion_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('subtotal', models.IntegerField()),
            ],
            options={
                'db_table': 'detallecompracliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('subtotal', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_cotizacion_empresa',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='CompraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='tienda.clienteb2c')),
            ],
            options={
                'db_table': 'compracliente',
            },
        ),
    ]
