# Generated by Django 5.0.6 on 2025-07-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecompracliente',
            options={'managed': True},
        ),
    ]
