# Generated by Django 5.0.6 on 2025-07-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_detallecompracliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compracliente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detallecompracliente',
            options={'managed': False},
        ),
    ]
